version: "3"
services:
  mongo:
    image: mongo:latest
    networks:
      - task-tracker
    volumes:
      - mongo-data:/data/db
  app:
    image: react-task-tracker
    ports: 
      - 5000:5000
    environment:
      - PROJ_ENV=production
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/tasks
    networks:
      - task-tracker
    depends_on:
      - mongo
networks:
  task-tracker:
    driver: bridge
volumes:
  mongo-data:
    driver: local