version: "3"
services:
  app:
    build: server/.
    ports: 
      - 5000:5000
    networks:
      - task-tracker
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - 27017:27017
    networks:
      - task-tracker
    volumes:
      - mongo-data:/data/db
networks:
  task-tracker:
    driver: bridge
volumes:
  mongo-data:
    driver: local